export const defaultPortfolioData = {
  profile: {
    name: "JLPortfolioDev",
    title: "IT Instructor - Full-Stack Developer",
    tagline:
      "Teaching practical software engineering while building systems that solve real institutional problems.",
    summary:
      "A passionate Information Technology instructor specializing in front-end development, programming fundamentals, and system development. Dedicated to helping students build practical technical skills through hands-on projects and real-world applications.",
    location: "Cebu City, Philippines",
    availability: "Available for collaboration, curriculum work, and system development projects.",
    focusTitle: "Academic systems, frontend development, and operational tooling.",
    focusSummary:
      "Experienced in building classroom management platforms, online proctoring tools, attendance systems, and automation workflows using modern web technologies, Node.js, Google Apps Script, and SQLite-backed applications.",
    yearsOfCraft: 5,
    projectsShipped: 4,
    profileImageUrl: "",
    profileImageAlt: "",
  },
  experiences: [
    {
      id: 1,
      title: "IT Instructor",
      organization: "Cebu Eastern College, Inc.",
      period: "School Year 2025-2026",
      description:
        "Leads front-end development, programming fundamentals, and system development sessions with a strong focus on hands-on output and industry-relevant workflows.",
      emphasis: "Teaching and curriculum delivery",
      sort_order: 1,
    },
    {
      id: 2,
      title: "BPO Employee",
      organization: "Customer / Technical / Chat Support",
      period: "During studies - 1 non-consecutive year",
      description:
        "Worked across customer, technical, and chat support functions, strengthening communication, troubleshooting, and service-oriented problem solving.",
      emphasis: "Support operations and technical communication",
      sort_order: 2,
    },
  ],
  certifications: [
    {
      id: 1,
      title: "In-Service Training and Teaching Seminars",
      issuer: "Cebu Eastern College, Inc.",
      period: "School Year 2025-2026",
      description:
        "Professional development focused on teaching practice, delivery, and classroom leadership.",
      sort_order: 1,
    },
    {
      id: 2,
      title: "Leadership Training",
      issuer: "Cebu Eastern College, Inc.",
      period: "October 2023",
      description:
        "Leadership-focused training designed to support guidance, initiative, and team coordination.",
      sort_order: 2,
    },
    {
      id: 3,
      title: "Data Analytics Training",
      issuer: "Cebu Eastern College, Inc.",
      period: "December 5, 2023",
      description: "Training centered on data handling, interpretation, and applied analytics workflows.",
      sort_order: 3,
    },
    {
      id: 4,
      title: "PSITE ICT Congress",
      issuer: "Cebu Eastern College, Inc.",
      period: "April 2023 and March 2024",
      description:
        "ICT congress participation to stay aligned with current tools, practices, and academic technology trends.",
      sort_order: 4,
    },
  ],
  skills: [
    { id: 1, name: "Frontend Development", category: "Core", level: "Advanced", sort_order: 1 },
    { id: 2, name: "Programming Fundamentals", category: "Core", level: "Advanced", sort_order: 2 },
    { id: 3, name: "System Development", category: "Core", level: "Advanced", sort_order: 3 },
    { id: 4, name: "React", category: "Web", level: "Advanced", sort_order: 4 },
    { id: 5, name: "Node.js", category: "Web", level: "Advanced", sort_order: 5 },
    { id: 6, name: "JavaScript", category: "Web", level: "Advanced", sort_order: 6 },
    { id: 7, name: "HTML & CSS", category: "Web", level: "Advanced", sort_order: 7 },
    { id: 8, name: "SQLite", category: "Data", level: "Intermediate", sort_order: 8 },
    { id: 9, name: "Google Apps Script", category: "Automation", level: "Advanced", sort_order: 9 },
    {
      id: 10,
      name: "Google Sheets Integration",
      category: "Automation",
      level: "Advanced",
      sort_order: 10,
    },
  ],
  projects: [
    {
      id: 1,
      slug: "class-schedule-management-attendance",
      title: "Class Schedule Management and Attendance Recording System",
      summary:
        "A Node.js-based academic operations system for schedule reminders, classroom coordination, and attendance recording.",
      description:
        "Designed to manage classroom activities, provide schedule reminders, and implement a more reliable attendance recording workflow for academic environments.",
      technologies: ["Node.js", "JSON", "HTML", "CSS", "JavaScript"],
      role: "Full-Stack Developer",
      category: "Education Systems",
      yearLabel: "2025",
      metricLabel: "Stack",
      metricValue: "Node.js + JSON",
      linkLabel: "",
      linkUrl: "",
      thumbnailUrl: "",
      useThumbnail: false,
      screenshots: [],
      featured: true,
      sort_order: 1,
    },
    {
      id: 2,
      slug: "anti-cheat-online-proctor",
      title: "Anti-Cheat Online Proctor Web Page System",
      summary:
        "A browser-based assessment monitoring experience that records responses and activity into Google Sheets.",
      description:
        "Built as an online proctoring tool for monitoring student activity during assessments while automating collection and review workflows through Google Apps Script and Google Sheets.",
      technologies: ["HTML", "CSS", "JavaScript", "Google Apps Script", "Google Sheets"],
      role: "Developer",
      category: "Assessment Tools",
      yearLabel: "2024",
      metricLabel: "Public Demo",
      metricValue: "Online",
      linkLabel: "Open demo",
      linkUrl: "https://itcec.github.io/online",
      thumbnailUrl: "",
      useThumbnail: false,
      screenshots: [],
      featured: true,
      sort_order: 2,
    },
    {
      id: 3,
      slug: "policy-violations-agreement-system",
      title: "IT Class Policies, Violations and Agreement System",
      summary:
        "A digital record platform for policies, agreements, and violation tracking that improves documentation transparency.",
      description:
        "Developed to centralize student agreements, class policies, and violation records into a clearer digital process for IT classes.",
      technologies: ["HTML", "CSS", "JavaScript", "Google Apps Script", "Google Sheets"],
      role: "Developer",
      category: "Academic Administration",
      yearLabel: "2024",
      metricLabel: "Public Demo",
      metricValue: "Policy Site",
      linkLabel: "Open site",
      linkUrl: "https://itcec.github.io/policy",
      thumbnailUrl: "",
      useThumbnail: false,
      screenshots: [],
      featured: false,
      sort_order: 3,
    },
    {
      id: 4,
      slug: "senior-citizen-information-system",
      title: "Senior Citizen Information System",
      summary:
        "A capstone web application for organizing resident records, reporting, and secure data management.",
      description:
        "Built as a web-based information management system for maintaining senior citizen records with user data management, reporting, and secure database storage.",
      technologies: ["PHP", "SQLite", "HTML", "CSS", "JavaScript", "Python"],
      role: "Lead Developer",
      category: "Community Systems",
      yearLabel: "Capstone",
      metricLabel: "Database",
      metricValue: "SQLite",
      linkLabel: "",
      linkUrl: "",
      thumbnailUrl: "",
      useThumbnail: false,
      screenshots: [],
      featured: true,
      sort_order: 4,
    },
  ],
  contacts: [
    {
      id: 1,
      label: "Email",
      value: "jlcabucosc.cec@gmail.com",
      icon: "mail",
      url: "mailto:jlcabucosc.cec@gmail.com",
      sort_order: 1,
    },
    {
      id: 2,
      label: "Contact Number",
      value: "+63 942 201 9206",
      icon: "call",
      url: "tel:+639422019206",
      sort_order: 2,
    },
    {
      id: 3,
      label: "Work Address",
      value: "Cebu Eastern College, Cebu City, Philippines",
      icon: "location_on",
      url: "",
      sort_order: 3,
    },
  ],
  socialLinks: [
    {
      id: 1,
      label: "GitHub",
      url: "https://github.com/jlcabucoscec",
      sort_order: 1,
    },
    {
      id: 2,
      label: "Facebook",
      url: "https://www.facebook.com/jl.king.56863",
      sort_order: 2,
    },
    {
      id: 3,
      label: "Instagram",
      url: "https://www.instagram.com/louiscabucos",
      sort_order: 3,
    },
  ],
  messages: [],
  mediaAssets: [],
};
